# -*- coding: utf-8 -*-
"""skillmate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14UKzQYXSfGmGQuAW2_GFBtaW3V256poJ
"""

import streamlit as st

st.set_page_config(page_title="SkillMate - Marketplace Akademik Mahasiswa", layout="wide")

# Hero Section
st.markdown("""
    <h1 style='text-align: center; font-size: 3em;'>Temukan & Tawarkan Skill-Mu di <span style="color:#4B8BBE;">SkillMate</span></h1>
    <p style='text-align: center; font-size: 1.2em;'>Marketplace akademik untuk mahasiswa: mentoring, desain, video editing, coding, hingga kerajinan tangan.</p>
""", unsafe_allow_html=True)

col1, col2 = st.columns(2)
with col1:
    st.button("🎯 Jelajahi Jasa")
with col2:
    st.button("🚀 Tawarkan Skill Anda")

st.markdown("---")

# Fitur Unggulan
st.subheader("🛠️ Fitur Unggulan")
cols = st.columns(5)
fitur = ["Mentoring", "Jasa Desain", "Edit Video", "Coding Project", "Kerajinan Tangan"]
icons = ["🧠", "🎨", "🎞️", "👨‍💻", "🪡"]
for col, f, icon in zip(cols, fitur, icons):
    col.metric(icon, f)

# Cara Kerja
st.markdown("## 🧭 Cara Kerja SkillMate")
st.markdown("""
1. **Buat Akun**
2. **Pilih atau Tawarkan Jasa**
3. **Chat & Deal**
4. **Transaksi Aman**
5. **Beri Ulasan**
""")

# Testimoni
st.markdown("## 💬 Testimoni Pengguna")
st.success("“Saya bisa dapet mentor buat belajar Python!” – Amanda, Mahasiswa Informatika")
st.info("“Jasa desainnya cepat & hasilnya bagus.” – Rafi, Mahasiswa DKV")

# Call to Action
st.markdown("## 🌟 Gabung Sekarang")
st.markdown("Lebih dari **500+ mahasiswa** telah menggunakan SkillMate.")
st.button("Daftar Sekarang")

# Footer
st.markdown("---")
st.markdown("SkillMate © 2025 | [Tentang Kami](#) | [FAQ](#) | [Kebijakan Privasi](#) | [Kontak](#)")